# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a1f2d812ae70ae92cfe08d61ff0b8a179b7d9953792b5b3b281f5f37edd4dc4669a986399a4b926733a333e78f4ea92a2c837494b16b16377b8fe11d37b7b45

test:
  secret_key_base: f005075afd46bbac5fa29f9224f7f13218f1291e598924d804082378d32f4c5d80316dbeda890ea1e104cff17769a94292ecafd60729e56c66552fdfc169db22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
